[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24"

[[headers]]
  for = "/*"
  [headers.values]
    Link = '''
      </BlissDay.webp>; rel=preload; as=image,
      </BlissNight.webp>; rel=preload; as=image,
      </camshaft_black.png>; rel=preload; as=image,
      </camshaft_white.jpg>; rel=preload; as=image,
      </headshot.webp>; rel=preload; as=image
    '''